name: Build Win

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y build-essential automake libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev libnuma-dev git

      - name: Install win dependencies
        run: sudo apt-get install -y mingw-w64 libz-mingw-w64-dev

      - name: Autogen
        run: ./autogen.sh

      - name: Configure
        run: ./configure --host=x86_64-w64-mingw32

      - name: make
        run: find /usr -name 'curl.h'

      - name: Configure
        run: ./configure --with-crypto --with-curl

      - name: make
        run: make

      - name: Winbuild-cross
        run: ./winbuild-cross.sh

      - uses: actions/upload-artifact@v2
        with:
          name: cpuminer-gr-avx2
          path: bin/
